-- 젯슨 감지 이벤트 연동 테이블 9개를 만듭니다.
-- 테이블명세서_임채현.hwp 의 CREATE TABLE 문을 그대로 옮기고 IF NOT EXISTS 만 붙였습니다.
-- TB_CAREGIVER(간병인은 현재 TB_EMP 로 처리), TB_EVENT_MEDIA(영상 녹화 미정)는 넣지 않았습니다.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS TB_LOCATION (
    LOCATION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WARD_ID BIGINT NOT NULL,
    LOCATION_NM VARCHAR(100) NOT NULL,
    LOCATION_TYPE VARCHAR(20) NOT NULL,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_LOCATION_WARD
        FOREIGN KEY (WARD_ID)
        REFERENCES TB_WARD(WARD_ID)
        ON DELETE RESTRICT,
    CONSTRAINT UK_LOCATION_WARD_NM
        UNIQUE (WARD_ID, LOCATION_NM),
    CONSTRAINT CK_LOCATION_NM
        CHECK (BTRIM(LOCATION_NM) <> ''),
    CONSTRAINT CK_LOCATION_TYPE
        CHECK (LOCATION_TYPE IN ('ROOM', 'COMMON'))
);

CREATE TABLE IF NOT EXISTS TB_EDGE_DEVICE (
    EDGE_DEVICE_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    HOSP_DIV_ID VARCHAR(30) NOT NULL,
    DEVICE_NM VARCHAR(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_SEEN_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPD_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_EDGE_DEVICE_HOSPITAL
        FOREIGN KEY (HOSP_DIV_ID)
        REFERENCES TB_HOSPITAL(HOSP_DIV_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_EDGE_DEVICE_NM
        CHECK (BTRIM(DEVICE_NM) <> '')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA (
    CAMERA_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    EDGE_DEVICE_ID BIGINT NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    SOURCE_REF TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_FRAME_AT TIMESTAMPTZ,
    LAST_INFER_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPD_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_CAMERA_EDGE_DEVICE
        FOREIGN KEY (EDGE_DEVICE_ID)
        REFERENCES TB_EDGE_DEVICE(EDGE_DEVICE_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_LOCATION
        FOREIGN KEY (LOCATION_ID)
        REFERENCES TB_LOCATION(LOCATION_ID)
        ON DELETE RESTRICT,
    CONSTRAINT UK_CAMERA_SOURCE
        UNIQUE (EDGE_DEVICE_ID, SOURCE_REF),
    CONSTRAINT CK_CAMERA_SOURCE_REF
        CHECK (BTRIM(SOURCE_REF) <> '')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA_CONFIG (
    CAMERA_ID BIGINT NOT NULL,
    CONFIG_VER INTEGER NOT NULL,
    CAPTURE_CONFIG JSONB NOT NULL,
    BED_ROI JSONB,
    BED_EXIT_CONFIG JSONB,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CAMERA_CONFIG
        PRIMARY KEY (CAMERA_ID, CONFIG_VER),
    CONSTRAINT FK_CAMERA_CONFIG_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_CAMERA_CONFIG_VER
        CHECK (CONFIG_VER > 0),
    CONSTRAINT CK_CAMERA_CAPTURE_CONFIG
        CHECK (JSONB_TYPEOF(CAPTURE_CONFIG) = 'object'),
    CONSTRAINT CK_CAMERA_BED_ROI
        CHECK (
            BED_ROI IS NULL
            OR JSONB_TYPEOF(BED_ROI) = 'object'
        ),
    CONSTRAINT CK_CAMERA_BED_EXIT_CONFIG
        CHECK (
            BED_EXIT_CONFIG IS NULL
            OR JSONB_TYPEOF(BED_EXIT_CONFIG) = 'object'
        ),
    CONSTRAINT CK_CAMERA_BED_CONFIG_PAIR
        CHECK (
            (BED_ROI IS NULL AND BED_EXIT_CONFIG IS NULL)
            OR
            (BED_ROI IS NOT NULL AND BED_EXIT_CONFIG IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS TB_MODEL_BUNDLE (
    MODEL_BUNDLE_ID BIGINT
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    BUNDLE_NM VARCHAR(100) NOT NULL,
    POSE_MODEL_NM VARCHAR(150) NOT NULL,
    POSE_MODEL_SHA256 CHAR(64) NOT NULL,
    FALL_MODEL_NM VARCHAR(150) NOT NULL,
    FALL_MODEL_SHA256 CHAR(64) NOT NULL,
    FEATURE_VER VARCHAR(50) NOT NULL,
    MODEL_CONFIG JSONB
        NOT NULL
        DEFAULT '{}'::JSONB,
    CRT_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    CONSTRAINT UK_MODEL_BUNDLE_NM
        UNIQUE (BUNDLE_NM),
    CONSTRAINT CK_MODEL_BUNDLE_NM
        CHECK (BTRIM(BUNDLE_NM) <> ''),
    CONSTRAINT CK_POSE_MODEL_NM
        CHECK (BTRIM(POSE_MODEL_NM) <> ''),
    CONSTRAINT CK_FALL_MODEL_NM
        CHECK (BTRIM(FALL_MODEL_NM) <> ''),
    CONSTRAINT CK_FEATURE_VER
        CHECK (BTRIM(FEATURE_VER) <> ''),
    CONSTRAINT CK_POSE_MODEL_SHA256
        CHECK (POSE_MODEL_SHA256 ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT CK_FALL_MODEL_SHA256
        CHECK (FALL_MODEL_SHA256 ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT CK_MODEL_CONFIG
        CHECK (JSONB_TYPEOF(MODEL_CONFIG) = 'object')
);

CREATE TABLE IF NOT EXISTS TB_CAMERA_SESSION (
    CAMERA_SESSION_ID UUID PRIMARY KEY,
    CAMERA_ID BIGINT NOT NULL,
    MODEL_BUNDLE_ID BIGINT NOT NULL,
    CONFIG_VER INTEGER NOT NULL,
    STARTED_AT TIMESTAMPTZ NOT NULL,
    ENDED_AT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_CAMERA_SESSION_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_SESSION_MODEL
        FOREIGN KEY (MODEL_BUNDLE_ID)
        REFERENCES TB_MODEL_BUNDLE(MODEL_BUNDLE_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_CAMERA_SESSION_CONFIG
        FOREIGN KEY (CAMERA_ID, CONFIG_VER)
        REFERENCES TB_CAMERA_CONFIG(CAMERA_ID, CONFIG_VER)
        ON DELETE RESTRICT,
    CONSTRAINT UK_CAMERA_SESSION_CAMERA
        UNIQUE (CAMERA_SESSION_ID, CAMERA_ID),
    CONSTRAINT CK_CAMERA_SESSION_CONFIG_VER
        CHECK (CONFIG_VER > 0),
    CONSTRAINT CK_CAMERA_SESSION_TIME
        CHECK (
            ENDED_AT IS NULL
            OR ENDED_AT > STARTED_AT
        )
);

CREATE TABLE IF NOT EXISTS TB_DETECTION_EVENT (
    EVENT_ID UUID PRIMARY KEY,
    CAMERA_ID BIGINT NOT NULL,
    CAMERA_SESSION_ID UUID NOT NULL,
    LOCATION_ID BIGINT NOT NULL,
    TRACK_ID INTEGER,
    EVENT_TYPE VARCHAR(20) NOT NULL,
    DECISION_ST VARCHAR(10) NOT NULL,
    EVENT_AT TIMESTAMPTZ NOT NULL,
    DECISION_SCORE DOUBLE PRECISION,
    EVENT_DETAIL JSONB
        NOT NULL
        DEFAULT '{}'::JSONB,
    CRT_DT TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),
    CONSTRAINT FK_DETECTION_EVENT_CAMERA
        FOREIGN KEY (CAMERA_ID)
        REFERENCES TB_CAMERA(CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_DETECTION_EVENT_LOCATION
        FOREIGN KEY (LOCATION_ID)
        REFERENCES TB_LOCATION(LOCATION_ID)
        ON DELETE RESTRICT,
    CONSTRAINT FK_DETECTION_EVENT_SESSION
        FOREIGN KEY (CAMERA_SESSION_ID, CAMERA_ID)
        REFERENCES TB_CAMERA_SESSION(CAMERA_SESSION_ID, CAMERA_ID)
        ON DELETE RESTRICT,
    CONSTRAINT CK_DETECTION_EVENT_DECISION
        CHECK (
            (
                EVENT_TYPE = 'FALL'
                AND DECISION_ST IN ('CONFIRMED', 'SUSPECTED')
            )
            OR
            (
                EVENT_TYPE = 'BED_EXIT'
                AND DECISION_ST = 'CONFIRMED'
            )
        ),
    CONSTRAINT CK_DETECTION_TRACK_ID
        CHECK (
            TRACK_ID IS NULL
            OR TRACK_ID >= 0
        ),
    CONSTRAINT CK_DETECTION_EVENT_DETAIL
        CHECK (
            JSONB_TYPEOF(EVENT_DETAIL) = 'object'
        )
);

CREATE TABLE IF NOT EXISTS TB_EVENT_ACTION (
    ACTION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID UUID NOT NULL,
    HANDLER_ID VARCHAR(20) NOT NULL,
    PATIENT_NM VARCHAR(50) NOT NULL,
    ACTION_CONTENT VARCHAR(1000) NOT NULL,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_EVENT_ACTION_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES TB_DETECTION_EVENT(EVENT_ID),
    CONSTRAINT FK_EVENT_ACTION_HANDLER
        FOREIGN KEY (HANDLER_ID)
        REFERENCES TB_EMP(EMP_ID),
    CONSTRAINT UK_EVENT_ACTION_EVENT
        UNIQUE (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS TB_SMS_SEND_HISTORY (
    SMS_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID UUID NOT NULL,
    USER_TYPE VARCHAR(10) NOT NULL,
    USER_ID VARCHAR(20) NOT NULL,
    PHONE_NO VARCHAR(20) NOT NULL,
    MESSAGE_CONTENT VARCHAR(500) NOT NULL,
    SEND_STATUS VARCHAR(10) NOT NULL,
    SEND_DT TIMESTAMPTZ,
    CRT_DT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_SMS_SEND_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES TB_DETECTION_EVENT(EVENT_ID),
    CONSTRAINT CK_SMS_SEND_USER_TYPE
        CHECK (USER_TYPE IN ('EMP', 'CAREGIVER')),
    CONSTRAINT CK_SMS_SEND_STATUS
        CHECK (SEND_STATUS IN ('SUCCESS', 'FAILED'))
);

COMMIT;
